# Generated by Django 2.1.5 on 2019-02-27 20:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('population', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('arrive_by', models.FloatField(default=0.0)),
                ('leave_at', models.FloatField(default=0.0)),
                ('transit_mode', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(1, 'Transit'), (2, 'Driving'), (3, 'Private')], default=1, max_length=3), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_mode', models.IntegerField(choices=[(1, 'Transit'), (2, 'Driving'), (3, 'Private')])),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_time', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('start_time', models.FloatField(default=0.0)),
                ('transfer_time', models.FloatField(default=0.0)),
                ('eager_time', models.FloatField(default=0.0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gg506.City')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gg506.Persona')),
            ],
        ),
    ]
