# Generated by Django 2.1.5 on 2019-02-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gg506', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('number', models.IntegerField(choices=[(1, 'Transit'), (2, 'Driving'), (3, 'Private')])),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='transit_mode',
        ),
        migrations.AddField(
            model_name='persona',
            name='mode',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='gg506.Mode'),
            preserve_default=False,
        ),
    ]
