# Generated by Django 2.1.5 on 2019-02-27 22:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gg506', '0003_auto_20190227_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
