# Generated by Django 2.1.5 on 2019-03-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gg506', '0004_auto_20190227_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='city',
        ),
        migrations.AddField(
            model_name='route',
            name='city_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='city_from', to='gg506.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='city_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='gg506.City'),
            preserve_default=False,
        ),
    ]
