# Generated by Django 2.1.5 on 2019-03-01 16:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gg506', '0005_auto_20190301_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
