# Generated by Django 2.1.5 on 2019-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg506', '0006_auto_20190301_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='day',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
