# Generated by Django 2.1.5 on 2019-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg506', '0008_da_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hub',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hub',
            name='transit_mode',
            field=models.IntegerField(choices=[(1, 'Transit'), (2, 'Driving'), (3, 'Private')], default=1),
            preserve_default=False,
        ),
    ]
