# Generated by Django 2.1.5 on 2019-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg506', '0010_interaroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='da',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
